/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.List;
import javax.swing.DefaultListModel;
import project.database.DBBill;
import project.database.DatabaseManager;

/**
 *
 * @author chittle
 */
public class LoadBillPanel extends javax.swing.JPanel {

  private MainFrame mainFrame;
  private DefaultListModel<DBBill> billsListModel;

  /**
   * Creates new form LoadBillPanel
   */
  public LoadBillPanel(MainFrame mainFrame) {
    this.mainFrame = mainFrame;
    initComponents();
    billsListModel = new DefaultListModel<DBBill>();
    billsList.setModel(billsListModel);
  }

  public LoadBillPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loadBillTitleLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    billsList = new javax.swing.JList();
    loadBillButton = new javax.swing.JButton();
    backButton = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(800, 600));

    loadBillTitleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    loadBillTitleLabel.setText("Load Bill");

    billsList.setModel(new DefaultListModel());
    billsList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        billsListMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(billsList);

    loadBillButton.setText("Load");
    loadBillButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadBillButtonActionPerformed(evt);
      }
    });

    backButton.setText("Back");
    backButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(322, 322, 322)
            .addComponent(loadBillTitleLabel))
          .addGroup(layout.createSequentialGroup()
            .addGap(346, 346, 346)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(backButton)
              .addComponent(loadBillButton)))
          .addGroup(layout.createSequentialGroup()
            .addGap(191, 191, 191)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(232, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(loadBillTitleLabel)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(loadBillButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(backButton)
        .addContainerGap(175, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    mainFrame.showMainPanel();
  }//GEN-LAST:event_backButtonActionPerformed

  private void loadBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBillButtonActionPerformed
    loadBillEvent();
  }//GEN-LAST:event_loadBillButtonActionPerformed

  private void billsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsListMouseClicked
    if (evt.getClickCount() == 2) {
      loadBillEvent();
    }
  }//GEN-LAST:event_billsListMouseClicked

  private void loadBillEvent() {
    int index = billsList.getSelectedIndex();
    if (index != -1) {
      DBBill bill = billsListModel.getElementAt(index);
      mainFrame.loadBill(bill);
    }
  }
  
  public void readBillsFromDB() {
    DatabaseManager db = new DatabaseManager();
    List<DBBill> bills = db.getBills();
    billsListModel.clear();
    for (DBBill bill : bills) {
      billsListModel.addElement(bill);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backButton;
  private javax.swing.JList billsList;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton loadBillButton;
  private javax.swing.JLabel loadBillTitleLabel;
  // End of variables declaration//GEN-END:variables
}
