/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author chittle
 */
public class MainPanel extends javax.swing.JPanel {

  private MainFrame mainFrame;
  private ArrayList<Bill> bills;
  private DefaultListModel<Bill> billsListModel;
  /**
   * Creates new form MainPanel
   */
  public MainPanel(MainFrame mainFrame) {
    this.mainFrame = mainFrame;
    initComponents();
    billsListModel = new DefaultListModel<Bill>();
    billsList.setModel(billsListModel);
  }

  public MainPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    billsLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    billsList = new javax.swing.JList();
    loadBillButton = new javax.swing.JButton();
    newBillButton = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    imageIconLabel = new javax.swing.JLabel();
    sloganLabel = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setPreferredSize(new java.awt.Dimension(800, 600));

    billsLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    billsLabel.setText("Bills");

    billsList.setModel(new DefaultListModel());
    billsList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        billsListMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(billsList);

    loadBillButton.setText("Load Bill");
    loadBillButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadBillButtonActionPerformed(evt);
      }
    });

    newBillButton.setText("New Bill");
    newBillButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newBillButtonActionPerformed(evt);
      }
    });

    jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    imageIconLabel.setIcon(new javax.swing.ImageIcon("/home/chittle/development/311project/src/res/logo.png")); // NOI18N

    sloganLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
    sloganLabel.setText("\"You Can't Beat Our Meat\"");

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/contact.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(imageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addComponent(sloganLabel)))
        .addContainerGap(21, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(31, 31, 31))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(imageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sloganLabel)
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(164, 164, 164)
            .addComponent(billsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(newBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(loadBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(23, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(57, 57, 57)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(billsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(newBillButton)
              .addComponent(loadBillButton))))
        .addContainerGap(141, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void newBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBillButtonActionPerformed
    mainFrame.openNewBill();
  }//GEN-LAST:event_newBillButtonActionPerformed

  private void loadBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBillButtonActionPerformed
    mainFrame.openLoadBillView();
  }//GEN-LAST:event_loadBillButtonActionPerformed

  private void billsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsListMouseClicked
    if (evt.getClickCount() == 2) {
      int index = billsList.getSelectedIndex();
      if (index != -1) {
        mainFrame.openBill(index);
      }
    }
  }//GEN-LAST:event_billsListMouseClicked

  public void setBillsList(ArrayList<Bill> bills) {
    this.bills = bills;
    revalidateBillsList();
  }
  
  public void revalidateBillsList() {
    billsListModel.clear();
    for (Bill bill : bills) {
      billsListModel.addElement(bill);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel billsLabel;
  private javax.swing.JList billsList;
  private javax.swing.JLabel imageIconLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton loadBillButton;
  private javax.swing.JButton newBillButton;
  private javax.swing.JLabel sloganLabel;
  // End of variables declaration//GEN-END:variables
}
