/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JLabel;

/**
 *
 * @author chittle
 */
public class ReceiptPanel extends javax.swing.JPanel {

  private MainFrame mainFrame;
  private Bill bill;

  /**
   * Creates new form ReceiptPanel
   */
  public ReceiptPanel(MainFrame mainFrame) {
    this.mainFrame = mainFrame;
    initComponents();
  }

  public ReceiptPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    receiptTable = new javax.swing.JTable();
    taxLabel = new javax.swing.JLabel();
    saveBillButton = new javax.swing.JButton();
    receiptTitleLabel = new javax.swing.JLabel();
    backButton = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(800, 600));

    receiptTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(receiptTable);

    taxLabel.setText("Tax Label");

    saveBillButton.setText("Save Bill");
    saveBillButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveBillButtonActionPerformed(evt);
      }
    });

    receiptTitleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    receiptTitleLabel.setText("Receipt");

    backButton.setText("Back");
    backButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(329, 329, 329)
            .addComponent(receiptTitleLabel))
          .addGroup(layout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(saveBillButton)
                .addGap(18, 18, 18)
                .addComponent(taxLabel)))))
        .addContainerGap(64, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(receiptTitleLabel)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(backButton)
          .addComponent(saveBillButton)
          .addComponent(taxLabel))
        .addContainerGap(154, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    mainFrame.showBillPanel();
  }//GEN-LAST:event_backButtonActionPerformed

  private void saveBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBillButtonActionPerformed
    mainFrame.saveBill();
  }//GEN-LAST:event_saveBillButtonActionPerformed

  public void setBill(Bill b) {
    this.bill = b;
    receiptTable.setModel(bill);
  }
  
  public JLabel getTaxLabel() {
    return this.taxLabel;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable receiptTable;
  private javax.swing.JLabel receiptTitleLabel;
  private javax.swing.JButton saveBillButton;
  private javax.swing.JLabel taxLabel;
  // End of variables declaration//GEN-END:variables
}
